### PR TITLE
[Fixes #12] Fixed `+` encoding to `%2B`

### LINKED ISSUE #12: encodeValue does not encode "+" to "%2B"

### PR DESCRIPTION
**Pull request by korotovsky**

### CODE REVIEW

**Comment by korotovsky** [comment]
@trowski Probably we have to exclude `[` and `]` from this regexp as well

**Comment by trowski** [comment]
Yes, in fact I think `!$&'()[]*+,:;=/%` all need to be removed from that regex. Does this sound correct?

**Comment by korotovsky** [comment]
No, we have to remove `[`, `]`, `+`, `=`, `/`, `%`, `&` and `'`.

**Comment by nexor** [comment]
Сould we just use `rawurlencode` function instead of this method ?

**Comment by trowski** [comment]
@nexor The function is using `rawurlencode()` to replace characters, but some characters should not be encoded, particularly those that may already be an encoded character.

@korotovsky Why only those characters? Based on the [URI RFC](https://www.ietf.org/rfc/rfc2396.txt), the only excluded characters should be alphanumeric plus `-`, `_`, `.`, `!`, `~`, `*`, `'`, `(`, and `)` (see section 2.3).

**Comment by korotovsky** [comment]
@trowski Probably we should follow URI RFC, but my suggestion was based on Google Chrome 47 behavior.

**Comment by korotovsky** [comment]
As I see this commit is already in `master`, so I close this PR.

**Comment by trowski** [comment]
I excluded other characters from the URI RFC as well except `[` and `]`. Should that be fine or is there a reason to encode them as well?

**Comment by korotovsky** [comment]
Google Chrome encodes it :) RFC says that we should not... I'm confused.

**Comment by trowski** [comment]
Actually the RFC says `[` and `]` should be encoded. I thought Google Chrome was not encoding them. Probably means it should be encoded here as well.

**Comment by korotovsky** [comment]
Then we have to encode them. I misunderstood you.

**Pull request closed without merging**
